### ISSUE TITLE
An unhandled exception occurred: listen EACCES: permission denied 127.0.0.1:8080

### ISSUE THREAD

**Issue by shylendramadda** [okta/samples-js-angular#87]
After doing `npm install` when I run `ng serve` I am getting this error:

An unhandled exception occurred: listen EACCES: permission denied 127.0.0.1:8080

unable to run the project.

**Comment by swiftone** [comment]
EACCESS is a permission from the local system - Usually I see this if I'm running another server (or another instance of the same server) on the same port (8080 in this case).  

Unfortunately, how to check your system to see what is already bound to a port will vary depending on your OS, and is a bit outside the scope of the sample docs.

**Comment by mraible** [comment]
You can install [fkill-cli](https://www.npmjs.com/package/fkill-cli) to kill processes running on a certain port.

```
npm i -g fkill-cli
fkill :8080
```

**Comment by aarongranick-okta** [comment]
You can probably use the `--port` cli option to serve on a different port. However, you would also need to adjust your login redirect URI to use the same port. https://angular.io/cli/serve

**Comment by shylendramadda** [comment]
Okay, thanks @swiftone let me check this and let you know.

**Comment by shylendramadda** [comment]
Now I stopped my server which is running on the same port 8080. Now I found this error:
`An unhandled exception occurred: Environment variable ISSUER must be set. See README.md
See "C:\Users\myPC\AppData\Local\Temp\ng-LwessF\angular-errors.log" for further details.`

I already set the `ISSUER` and `CLIENT_ID` in the environment.ts

`export const environment = {
  production: false,
  ISSUER: 'https://myoktadomain.com/oauth2/default',
  CLIENT_ID: '0oasgasdhdjhgasjdbgj' // it's a dummy one
};`

**Comment by shylendramadda** [comment]
> You can install [fkill-cli](https://www.npmjs.com/package/fkill-cli) to kill processes running on a certain port.
> 
> ```
> npm i -g fkill-cli
> fkill :8080
> ```

I tried this here is the log
fkill :8080
```
? Error killing process. Would you like to use the force? Yes
AggregateError:
    Error: Killing process :8080 failed: Process doesn't exist
        at Array.map (<anonymous>)
        at fkill (C:/Users/shyle/AppData/Roaming/npm/node_modules/fkill-cli/node_modules/fkill/index.js:128:9)
        at async Object.handleFkillError (C:/Users/shyle/AppData/Roaming/npm/node_modules/fkill-cli/interactive.js:125:4)      
    at fkill (C:\Users\shyle\AppData\Roaming\npm\node_modules\fkill-cli\node_modules\fkill\index.js:128:9)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Object.handleFkillError (C:\Users\shyle\AppData\Roaming\npm\node_modules\fkill-cli\interactive.js:125:4)
```

**Comment by suresh444** [comment]
> > You can install [fkill-cli](https://www.npmjs.com/package/fkill-cli) to kill processes running on a certain port.
> > ```
> > npm i -g fkill-cli
> > fkill :8080
> > ```
> 
> I tried this here is the log
> fkill :8080
> 
> ```
> ? Error killing process. Would you like to use the force? Yes
> AggregateError:
>     Error: Killing process :8080 failed: Process doesn't exist
>         at Array.map (<anonymous>)
>         at fkill (C:/Users/shyle/AppData/Roaming/npm/node_modules/fkill-cli/node_modules/fkill/index.js:128:9)
>         at async Object.handleFkillError (C:/Users/shyle/AppData/Roaming/npm/node_modules/fkill-cli/interactive.js:125:4)      
>     at fkill (C:\Users\shyle\AppData\Roaming\npm\node_modules\fkill-cli\node_modules\fkill\index.js:128:9)
>     at processTicksAndRejections (internal/process/task_queues.js:97:5)
>     at async Object.handleFkillError (C:\Users\shyle\AppData\Roaming\npm\node_modules\fkill-cli\interactive.js:125:4)
> ```



> After doing `npm install` when I run `ng serve` I am getting this error:
> 
> An unhandled exception occurred: listen EACCES: permission denied 127.0.0.1:8080
> 
> unable to run the project.

how did you resolve this??

**Comment by TKaluthanthri** [comment]
I had the same issue I solved this by restarting the Windows NAT 

open CMD/PowerShell and type **net stop winnat** and then **net start winnat**

**Comment by francodev25** [comment]
Well, Google bring me here.  I got the same issue with Vue3 by running.
` npm run dev`

**I Solved** this by adding a flag '--port 3001' (Which means : _use another port by default_)

`npm run dev --port 3001`

Maybe this issue is due that other app is using the same port. 
Hope you solve it!  :smiley: :+1:

**Comment by ChichebeDarlington** [comment]
please help me out still getting same error after trying all the possible solutuon listed here.

Error: listen EACCES: permission denied 8000;

**Comment by SaurabhBose** [comment]
I would suggest use command prompt (as admin) and 
`net stop winnat`
`net start winnat`
This should free up the ports.

**Comment by Ibinola** [comment]
thanks @SaurabhBose it worked for me!

**Comment by Karanpal97** [comment]
tried every thing which is mentioned above, not working plz help me to get out of this

**Comment by IasmimCristina** [comment]
Me too! T_T

**Comment by SaurabhBose** [comment]
If my earlier solution of 
```
net stop winnat
net start winnat
```
did not work: 
1. Are you running the cmd as admin? If not, _Right-click on the application or command prompt you're using to start the server and select "Run as administrator"._ 
2. `netstat -ano | findstr :8080` : and try stopping processes binding on that port.

**Comment by dumindu-dev** [comment]
On Windows System, restarting the service "Host Network Service", resolved the issue.

Original answer: https://stackoverflow.com/a/65434145/12731030
